name: job_plus
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_onboarding_slider: ^1.0.11
  get: ^4.6.5
  hexcolor: ^3.0.1
  introduction_screen: ^3.1.8
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets\fonts\Roboto.ttf
  assets:
    - assets/images/logo.svg
    - assets/images/logo.png
    - assets/images/logoDark.png
    - assets/images/OnBording1.png
    - assets/images/OnBording2.png
    - assets/images/OnBording3.png


        
